name: Build and deploy container app to Azure Container Registry

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true  # Ensures submodules are included

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AzureAppService_ContainerRegistry }}
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to ACR
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.AzureAppService_ContainerRegistry }}/meshview:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build for pull requests (without push)
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: meshview:pr-${{ github.event.number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 