name: Build and deploy container app to Azure Container Registry

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true  # Ensures submodules are included

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AzureAppService_ContainerRegistry }}
        username: ${{ secrets.AzureAppService_ContainerUsername }}
        password: ${{ secrets.AzureAppService_ContainerPassword }}

    - name: Build and push container image to ACR
      uses: docker/build-push-action@v6
      with:
        context: .   # Ensure Dockerfile is in the correct context
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.AzureAppService_ContainerRegistry }}/meshview:latest